version: "3.9"
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - myapp_network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - myapp_network
      
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - myapp_network

networks:
  myapp_network:

volumes:
  mysql_data: